### ISSUE TITLE
Performance different on X86 and ARM service

### ISSUE THREAD

**Issue by luoming17** [agenium-scale/nsimd#100]
Hi, I wote some code and test their performance on X86 and ARM, and I got 50% performance enhance on X86, but 55% performance reduction on ARM. This did not meet my expectations and I expected the same performance enhance from them on different machines.

I use CMake to compile my project, and here are some code in my CMakeLists.txt
```
if(${ARCHITECTURE} STREQUAL "x86_64")
    add_compile_options(-DSSE42 -DFMA -march=skylake)
else()
    add_compile_options(-DAARCH64 -march=armv8.2-a)
endif()
```
I build nsimd with```CMAKE_ARGS -Dsimd=SSE42``` on X86 and  ```CMAKE_ARGS -Dsimd=AARCH64``` on ARM.

To use a 128-bit register, I have some c++ code like this:
```
#if defined(NSIMD_X86)  // X86 platform
    using nsimd_t = nsimd::sse42;
#else   // ARM platform
    #if NSIMD_WORD_SIZE == 32
        using nsimd_t = nsimd::neon128;
    #else
        using nsimd_t = nsimd::aarch64;
    #endif
#endif

template <typename T>
using pack128_t = nsimd::pack<T, 1, nsimd_t>;
```

I run ```lscpu``` on the ARM service and I got this:
```
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    1
Core(s) per socket:    64
Socket(s):             2
NUMA node(s):          4
Model:                 0
BogoMIPS:              200.00
L1d cache:             64K
L1i cache:             64K
L2 cache:              512K
L3 cache:              65536K
NUMA node0 CPU(s):     0-31
NUMA node1 CPU(s):     32-63
NUMA node2 CPU(s):     64-95
NUMA node3 CPU(s):     96-127
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop
```

Am I using the wrong compile options? Why it reduce performance on ARM service?

**Comment by gquintin** [comment]
Hi @luoming17, it depends on so many things that it is impossible to answer you without more informations:

- What is the algorithm you are running?
- What is the Intel machine exactly?
- What is the Arm machine exactly? (Raspberry Pi, Smartphone, server...)
- What is your metric? What do you mean exactly by "50% performance enhance" and "55% performance reduction on ARM" ?

The only job of NSIMD is basically to ensure that what you type in your C or C++ code is properly translated into assembly. So if you write `a + b` the job of NSIMD is to be sure that it is translated into:
- `_mm_add_ps(a, b)` for Intel SSE 4.2
- `vaddq_f32(a, b)` for Aarch64.

You can check that by looking at the assembly of your binary. If it the case then NSIMD works properly. Getting good performances out of it requires some investigations. Moreover it is really surprising to expect the same level of performances from two chips that are completely different (Arm vs. Intel)

**Comment by luoming17** [comment]
Hi @gquintin , because of confidentiality agreement, I cant post my code, I'm sorry.
I have solved my problem, I found out the reason was that a function was called billions of times, and it should add static inline declaration.
