### ISSUE TITLE
NSIMD generates too much assembly 

### ISSUE THREAD

**Issue by raphaelthegreat** [agenium-scale/nsimd#106]
I recently found the need for a cross platform simd library and nsimd seems to be the perfect fit. However after testing a bit on Godbolt I discovered that even with optimizations enabled, the amount of assembly code generated is very large, exceeding even scalar operations in many cases. For example, implementing a simple add function results in over 15 lines of assembly:
![image](https://user-images.githubusercontent.com/47210458/154534362-a5226155-ca8c-4c33-ac8e-cbcfea4a1ccf.png)

Compared to this, using SSE intrinsics directly results in the expected much more compact assembly:
![image](https://user-images.githubusercontent.com/47210458/154533985-927658c0-91fd-4e9a-ab85-96664de51f11.png)

I have made sure to enable optimizations and the AVX2 GCC flag. I thought that maybe the integer operations were emulated as mentioned in the documentation so I also tried the same minimal example with floats, to no avail:
![image](https://user-images.githubusercontent.com/47210458/154532566-3723771e-f223-440e-94f3-5636e2545e68.png)

I wouldn't mind having to deal with some overhead but this too much to be normal. I also tested nsimd::if_else and it also suffers from this:
![image](https://user-images.githubusercontent.com/47210458/154533121-bfa29a5f-3736-4d44-87eb-976b1d67191e.png)

Is this intentional? Is this a bug? Is there any way to improve the quality of the generated code?

**Comment by eschnett** [comment]
I believe you are misunderstanding the "length" argument of a pack. You should probably set it to `1` (not `4`) to create a pack that has the natural size for your architecture. Choosing a larger value allows setting up SIMD vectors with a length that is a multiple of the natural hardware vector length. In other words, your nsimd examples are working on 16 elements, not just 4, and the code is thus much longer than expected. You are also seeing a lot of code related to loading and storing function arguments from and to the stack; these instructions will go away if the function is inlined, or is used inside a larger function.

I usually just use `pack<double>`, without specifying the length. The SIMD length is chosen automatically by nsimd.

As a test, you can evaluate `sizeof(pack<float, 4>)`.

**Comment by raphaelthegreat** [comment]
> I believe you are misunderstanding the "length" argument of a pack. You should probably set it to `1` (not `4`) to create a pack that has the natural size for your architecture. Choosing a larger value allows setting up SIMD vectors with a length that is a multiple of the natural hardware vector length. In other words, your nsimd examples are working on 16 elements, not just 4, and the code is thus much longer than expected. You are also seeing a lot of code related to loading and storing function arguments from and to the stack; these instructions will go away if the function is inlined, or is used inside a larger function.
> 
> I usually just use `pack<double>`, without specifying the length. The SIMD length is chosen automatically by nsimd.
> 
> As a test, you can evaluate `sizeof(pack<float, 4>)`.

Thanks for pointing it out. The code looks much cleaner now. But if size of the vector depends on the architecture provided, is there any cross platform way of defining the size? In addition, though, I have been facing numerous build errors on compilers that aren't GCC when using the nsimd::cvt function. For example:

![image](https://user-images.githubusercontent.com/47210458/154557174-5fe28691-6eab-4bf1-b708-23666652c5f3.png)
GCC

![image](https://user-images.githubusercontent.com/47210458/154557282-2796b89d-074b-4000-b457-b467072824b0.png)
Clang

![image](https://user-images.githubusercontent.com/47210458/154557572-ea0277fc-7e63-4990-9269-bde1b7475922.png)
MSVC

**Comment by eschnett** [comment]
I am not aware of a way to define the SIMD vector size. The suggested approach is to let nsimd choose the optimal vector length, and then to inquire the actual vector length at compile time. This allows efficient loop vectorization when traversing arrays in loops.

I am not encountering any such errors. I uses nsimd regularly, on various systems. I usually build with GCC 11.2 (as you do), and I specify `-std=c++17` as well.

Most SIMD hardware works on a fixed number of bits. Thus converting from `4xi32` to `4xi16` is not a natural operation. The natural operation would generate an `8xi16` vector, presumably from two `4xi32` inputs. Maybe you need to use `downcvt` instead of `cvt`?

**Comment by raphaelthegreat** [comment]
> I am not aware of a way to define the SIMD vector size. The suggested approach is to let nsimd choose the optimal vector length, and then to inquire the actual vector length at compile time. This allows efficient loop vectorization when traversing arrays in loops.
> 
> I am not encountering any such errors. I uses nsimd regularly, on various systems. I usually build with GCC 11.2 (as you do), and I specify `-std=c++17` as well.
> 
> Most SIMD hardware works on a fixed number of bits. Thus converting from `4xi32` to `4xi16` is not a natural operation. The natural operation would generate an `8xi16` vector, presumably from two `4xi32` inputs. Maybe you need to use `downcvt` instead of `cvt`?

What I want to do is take each element of the int32 vector and cast it down to int16 without reducing the vector size (in elements). With intrinsics this can be done to my knowledge with _mm_cvtps_pi16 so I assumed that nsimd::cvt would work based on the similar name.

**Comment by raphaelthegreat** [comment]
Closing is now as resolved
