### ISSUE TITLE
Feature request: shuffle, split, tofloat, toint support

### ISSUE THREAD

**Issue by otristan** [agenium-scale/nsimd#2]
Unless I am missing the correct naming, it looks like
nsimd misses some functions like shuffle, split, tofloat, toint

Are those planned ?

Thanks !

**Comment by gquintin** [comment]
For tofloat and toint, I think what you are looking for is `cvt`. You can see its use in tests files.

```c++
int main() {
  nsimd::pack<int> a;
  nsimd::pack<float> b;
  a = nsimd::cvt<nsimd::pack<int>>(b); // converts from floats to ints
  b = nsimd::cvt<nsimd::pack<float>>(a); // converts from ints to floats
  return 0;
}
```

We will add `split` which will not be called `split` to convert SIMD vectors containing N X-bits wide data into 2 SIMD vectors of N (2 * X)-bits wide data. We will also provide the corresponding `group` function that will not be called `group`.

Concerning shuffle, we are planning to add them. We will most likely begin by those that are vector-length agnostic.

You are welcome to add/wrap intrinsics, the CONTRIBUTE.md file contains a tutorial on how to do it. It is currently in its first version so do not hesitate to ask questions. We have tried to design NSIMD in such a way that it is really simple to add intrinsics.

**Comment by gquintin** [comment]
Hi otristan,

`Split` and `group` have been added. They are respectively called `upcvt` and `downcvt`. I will close this issue and create one dedicated only to shuffles.
