### ISSUE TITLE
Installs into "include/include"

### ISSUE THREAD

**Issue by eschnett** [agenium-scale/nsimd#22]
I just installed nsimd (master branch) on OS X, and the include files ended up in `$INSTALLDIR/include/include/nsimd`. Note the double `include/include` that probably shouldn't be there.

**Comment by ccharly** [comment]
Indeed. I'm fixing this. Thanks for the report.

**Comment by ccharly** [comment]
Should be fixed by now. I've already merged the PR. Could you try it again and confirm that it's working as intended? I'll close right after. Thanks.

**Comment by eschnett** [comment]
Confirmed; it's fine now.
