### ISSUE TITLE
Masked vector store functions?

### ISSUE THREAD

**Issue by eschnett** [agenium-scale/nsimd#23]
Does nsimd provide masked store functions (e.g. `vstoreu_masked` or similar)? I could not find any.

I am maintaining the SIMD library of the Einstein Toolkit (see https://bitbucket.org/cactuscode/cactusutils/src/master/Vectors/), and am interested in exploring a community supported approach. If there are no masked store intrinsics in nsimd, would you be interested in accepting a contribution? Could you provide a few rough guidelines for implementing this?

**Comment by gquintin** [comment]
NSIMD does not provide masked operators. We are of course very interesting in any contribution. The [CONTRIBUTE.md](https://github.com/agenium-scale/nsimd/blob/master/CONTRIBUTE.md) file contains a tutorial on how to add operators.

Concerning masked loads and stores it seems that there are two different "approaches" for a given operartor `op` (for `load` or `store`):
- Intel AVX-512 proposes `op`, `maskz_op` that puts zeros in inactive elements and `mask_op` that puts in inactive elements those coming from a extra SIMD vector.
- Arm SVE proposes only `op` which loads/stores active elements but does not do anything to the inactive ones.

I am not sure which approach is best. Maybe we should include all four flavors with the following naming:
- `op` which loads/stores without any mask.
- `mask_op` which loads/stores à la Arm SVE.
- `maskz_op` which loads/stores à la Intel AVX-512 `maskz_load`/`maskz_store`.
- `masko_op` (for mask with Other?) which loads/stores à la Intel AVX-512 `mask_load`/`mask_store`.

I am not sure if that should be done at the same time but we also have to think about masking the `load[au][234]`/`store[au][234]` operators.

From what I saw of your pull request #28  you have taken the `maskz_op`-approach. But you have only implemented the operators for AVX2 and for 64-bits and 32-bits types. This should be extended to all types for all SIMD extensions supported by NSIMD.

For SSE2 and SSE42 I think the store operators can make use of a combination of blend + `_mm_maskmoveu_si128`. For AVX you already did it with the intrinsc. When no intrinsics are provided I think that a for-loop is necessary. One cannot use blend if for example, the user uses masks to finish its data we do not want to write after the end of its allocated memory/buffer.

**Comment by eschnett** [comment]
@gquintin I am interested in vectorizing loops that have a size which does not evenly divide the vector size. The loop might also be parallelized, so that concurrent (multi-threaded) accesses to the same array must be possible. In other words, inactive vector elements must not be touched; things need to be tread safe as long as the active elements of a masked store do not overlap.

I don't understand the distinction between `mask_op` (which I intended to implement) and `masko_op`. I think these are the same for stores to memory.

Yes, I have not yet added code for all architectures, nor have I added tests nor documentation. And yes, the general fallback will have to be to store the elements as scalars.

**Comment by gquintin** [comment]
Ok, so in your case what you want is the `mask_op` flavor.

`Mask_store` could be implemented with the following

```c
void mask_store(float *dst, simd_vector src, simd_mask mask) {
    for (int i = 0; i < src.size; i++) {
        if (mask[i]) {
            dst[i] = src[i];
        }
    }
}
```

while `masko_store` could be implemented by the following:

```c
void masko_store(float *dst, simd_vector src, simd_mask mask, simd_vector other) {
    for (int i = 0; i < src.size; i++) {
        if (mask[i]) {
            dst[i] = src[i];
        } else {
            dst[i] = other[i];
        }
    }
}
```

And `maskz_store` is simply `masko_store(dst, src, mask, simd_all_zero)`.
