### ISSUE TITLE
When regenerating files, only write those files that changed

### ISSUE THREAD

**Issue by eschnett** [agenium-scale/nsimd#29]
When regenerating files, only write those files that changed. This would make it much faster to rebuild everything, especially the tests.

**Comment by gquintin** [comment]
We would love to have such a system. But it is difficult to get it right:
- Each test should then depends on a particular set of SIMD dependant headers. The `notb` function has no dependency on ARM but depends on `andnotb` on Intel and we do not want a build system system that behave differently w.r.t the CPU.
- Each test/bench should in fact depends on parts of the Python scripts that generates them. I am not sure such a system exists and I doubt that it would work properly.

Do you have any idea on how to improve the current build system?

**Comment by eschnett** [comment]
@gquintin I was not thinking of managing the Python dependencies. (I don't know how to do this.)

I was thinking of only changing the way the C and C++ files are written. Before they are written to their final destination, they are written to a temporary location, and compared against their existing counterpart (if any). If they are identical, the existing file is not replaced. This way, `make` sees that the C file did not change, and will not rebuild it nor its dependencies.

To speed up Python one could use multi-processing. I don't know the Python code well enough to understand its dependencies, or whether it would be possible to generate the C files concurrently.

**Comment by gquintin** [comment]
In the next release, generating code will be much faster. In fact it was coming from clang-format. Calling it for each generated file is costly. Moreover when developing the script `scripts/build-tests.sh` only compile selected tests speeding up the whole process. To select certain tests write into the file `targets.txt` regular expressions: one on each line. For example

```
gather
scatter
```

will only compile tests whose name contain "gather" or "scatter" as a substring.

**Comment by gquintin** [comment]
I am put the label "already fixed for next release" as for now, for us, it more than sufficient. What you describe would be great but not a priority for us right now. You are of course welcome to do a pull request if you have time.
