### ISSUE TITLE
Don't use unions for reinterpreting data

### ISSUE THREAD

**Issue by eschnett** [agenium-scale/nsimd#34]
The C++ standard does not allow using unions to reinterpret data as a different type, e.g. to access the bit patterns of a float (see e.g. <https://en.wikipedia.org/wiki/Type_punning#Use_of_union>). One has to use `memcpy` instead.

While GCC allows this as an extension to the C++ standard, other compilers do not. I don't recall exactly which compilers these are, but I have had trouble in the past while using the IBM XL or PGI compilers on non-Intel architectures.

**Comment by gquintin** [comment]
We are well aware of this but we do not know how to do this in a standardized way and we cannot use `memcpy`. We have experienced the `memcpy` approach and it gives bad performances. From our experience for "simple" code `memcpy` is well optimized by compilers, but for more complicated code one can see in the assembly an inline and unrolled call to `memcpy`. The following assembly is coming from such a case some months back:

```asm
xor   eax, eax
...
mov   BYTE PTR $T153[rbp-256], al
mov   BYTE PTR $T154[rbp-256], al
mov   BYTE PTR $T155[rbp-256], al
mov   BYTE PTR $T156[rbp-256], al
mov   BYTE PTR $T157[rbp-256], al
mov   BYTE PTR $T158[rbp-256], al
mov   BYTE PTR $T159[rbp-256], al
mov   BYTE PTR $T160[rbp-256], al
mov   BYTE PTR $T161[rbp-256], al
```

So if there is a simple-no overhead-c++98-standardized way to do it we will be very glad to implement it.

**Comment by eschnett** [comment]
I have generated vectorized code for years, and I have never encountered such and issue with `memcpy`. Maybe I was looking at different compilers, different versions, or different architectures. The code you showed above is clearly not acceptable.

In this case, one solution would be to generate `#ifdef` statements to check the compiler, and use unions if the compiler handles them correctly. If the compiler doesn't, you can switch to `memcpy`.

**Comment by gquintin** [comment]
I agree with you and I was thinking of this kind of solution even if I do not want to write `#ifdef` code. One other non standard possibility is to have something like this when supported by the compiler of course:

```c
unsigned int get_bits(float a) {
    return *( (unsigned int*)&a );
}
```

**Comment by eschnett** [comment]
I tried pointer casting; it does not work e.g. with GCC.

If you don't like `#ifdef`s in the auto-generated code, then you could introduce `reinterpret` functions for scalars into `nsimd.h`, which one can call in the auto-generated code. That means that there is a single, global `#ifdef` only.

**Comment by gquintin** [comment]
On branch `tet_1d` we are refactoring some code and all reinterprets will pass thourhg one single point in the Python code so that is will be easy to support different mechanisms. For now we will support:

- GCC and reinterpreting via unions
- All other compilers (including nvcc) with the `memcpy` approach

Maybe some reinterprets won't benefit from this right now but they will be fixed overtime.

**Comment by gquintin** [comment]
Note that NVCC and HIPCC have builtins that does exactly what we are looking for:

- For NVCC : <https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__INTRINSIC__CAST.html#group__CUDA__MATH__INTRINSIC__CAST>
- For HIPCC : <https://rocm-documentation.readthedocs.io/en/latest/ROCm_API_References/HIP-MATH.html#hip-math>

The complete list is of builtins is:
- `__double_as_longlong`
- `__float_as_int`
- `__float_as_uint`
- `__int_as_float`
- `__longlong_as_double`
- `__uint_as_float`

I am not aware of other builtins for other compilers.
