### ISSUE TITLE
Tests should special case rsqrt8

### ISSUE THREAD

**Issue by eschnett** [agenium-scale/nsimd#39]
The test case generator generates special code for `rsqrt11`. It should probably do the same for `rsqrt8`.

**Comment by gquintin** [comment]
I checked on my laptop and it seems that it does. What to you mean? Anyway concerning tests, the branch `power-support` improves testing and it will be merge soon with master.

**Comment by eschnett** [comment]
I am referring to lines 268 and 270 on the master branch of `egg/gen_tests.py`. These lines have special code for `rsqrt11`, but not for `rsqrt8`, which might indicate a bug.
