### ISSUE TITLE
Documentation on building/running tests is probably out of date.

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [agenium-scale/nsimd#49]
Hi

So, following the instructions, I ran cmake
```
 cmake .. -DSIMD=AVX2 -DDEV=1 -DBOOST_ROOT=/**/boost_1_72_0 -GNinja
```

It says:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    BOOST_ROOT
    DEV
```

Then: `ninja -j1 update` - unknown target

However,  running:
```
ninja -j 4 tests
ctest
```
Has worked, apparently successfully:  `100% tests passed, 0 tests failed out of 2691`

Was running on macos, I know - not a supported target, but I hope it will work since the tests passed.

**Comment by DenisYaroshevskiy** [comment]
Found more typos in other bis. Doesn't hurt much but still:


https://agenium-scale.github.io/nsimd/tutorials_basic_pack.html

When talking about storing
If the memory is not aligned, not recommented, you can use nsimd::loadu:

https://agenium-scale.github.io/nsimd/tutorials_basic_loop.html

No declaration of len if i += len is confusing.
oad the data from memory

https://agenium-scale.github.io/nsimd/tutorials_intermediate_dot_product.html

We are now going to use boost::simd::pack to vectorize this loop - not boost.

https://agenium-scale.github.io/nsimd/tutorials_intermediate_if_else.html

Link is broken: https://agenium-scale.github.io/src/threshold.cpp

https://agenium-scale.github.io/nsimd/tutorials_intermediate_nbody.html

This is an example of a problem of complexity - is np missing?
The formula to calculate the gravitational force between two objects is: ?? missing formula

https://agenium-scale.github.io/src/nbody.cpp - 404 lin

https://agenium-scale.github.io/nsimd/tutorials_advanced_runtime_simd.html

BOOST_SIMD_DEFAULT_SITE - probably not boost

https://agenium-scale.github.io/nsimd/tutorials_advanced_mandelbrot_set.html

This code is vectorized as follows: - missing function declaration. Link is broken. Todos.
Is this not finished?

FAQ:

use of bs namespace bs::aligned_store(v0, &output[i]);

**Comment by gquintin** [comment]
Hi Denis,

Sorry for the delay in our response. Yes some parts are bad copy/paste from Boost.SIMD. We do not need the `DEV` and `BOOST_ROOT` CMake variables anymore as we do not depend on Boost. Note that we are thinking of switching to [nsconfig](https://github.com/agenium-scale/nstools/tree/master/nsconfig) for several reasons:
- internally we do not use CMake as it is too slow (especially on Windows), does not support several compilers at once...
- we are adding support for CUDA and ROCm and the support of these in CMake is not trivial. For CUDA, [according to the version of CMake and the host system](<https://devblogs.nvidia.com/building-cuda-applications-cmake/>) the CMake code will be different. For ROCm, as there are far less users, we think that we will face problems.
- build files using `nsconfig` tend to be much smaller, hence less bugs, more readability, more maintainability.
- Nsconfig uses a Makefile-like syntax which makes it much much easier for people to understand and write.

Apple is not a platform we do *not* want. It is just that we do not have a MAC in-house for our tests. We are working on that. NSIMD should compile and run fine on MAC as we test on Linux with Clang. If you find any Apple-specific bug feel free to report them to us.

As for the documentation, we are working on three modules and we thinking of the best way to include module documentation nicely in our system. Once we will be decided, we will make a pass on all the documentation to fix all the mistakes you found out. Thank you for that by the way.

**Comment by DenisYaroshevskiy** [comment]
@gquintin - it was more FYI.
