### ISSUE TITLE
Feature Request : Better support of msvc compiler 

### ISSUE THREAD

**Issue by ThomasRetornaz** [agenium-scale/nsimd#6]
The variable NSIMD_CXX is misused in case of MSVC compiler
EG: NSIMD_CXX ==2014 for visual 2019 
eg: we can't check value like NSIMD_CXX < 201103L
to switch on allocator flavor

**Comment by gquintin** [comment]
Hi Thomas,

`NSIMD_CXX` is less precise than `__cplusplus`. It is used inside NSIMD as we do not want to write code with `#ifdef`'s for each standardized/yet to be standardized (C++1x, C++1y, C++1z, ...) version of the C++ language. We only focused on standardized versions. Plus we do not want to remember the official value of `__cplusplus` for each standardized versions of C++ hence the `NSIMD_CXX` macro.

If you wish to have a more precise value use `NSIMD__cplusplus` whose definition takes into account MSVC's specificity and is as follows.

```c++
#ifdef NSIMD_IS_MSVC
  #define NSIMD__cplusplus _MSVC_LANG
#else
  #define NSIMD__cplusplus __cplusplus
#endif
```

Maybe the most recent version of MSVC does not report a good value in `_MSVC_LANG` in which case a fix concerning the definition of `NSIMD__cplusplus` will be done.

**Comment by ThomasRetornaz** [comment]
Hi
You right this kind of stuff is painfull
Sorry i not read carefully the first time
In fact 
*NSIMD provide NSIMD_CXX define here https://github.com/agenium-scale/nsimd/blob/master/include/nsimd/nsimd.h#L94
*But check here https://github.com/agenium-scale/nsimd/blob/master/include/nsimd/nsimd.h#L676 
like if its NSIMD__cplusplus define i think it should be should be #if NSIMD_CXX >= 2011
Thanks
Regards
TR
