### ISSUE TITLE
Debug output in test cases?

### ISSUE THREAD

**Issue by eschnett** [agenium-scale/nsimd#70]
The files `nsimd.cpp` and `nsimd-all.cpp` output results via `printf`, as e.g. with the lines
```C++
  for (int i = 0; i < n; i++) {
    fprintf(stdout, "%f vs %f\n", double(buf[i]), double(-i * i));
  }
```

In the file `nsimd-all.cpp`, this output also differs from the condition that decides whether the test case succeeds or fails (a `+1` is missing).

**Comment by gquintin** [comment]
Hi Erik,

Those two tests are not meant to check that the computation of the square is correct. Their main purpose is to check that output, unrolling... works. Morevoer I do not understand why a `+1` is missing because my output is as follows.

```
{ 1.000000e+00, 1.000000e+00 }{ 1.000000, 1.000000 }{ 1, 1 }
{ 1, 1 }
-0.000000 vs 0.000000
-1.000000 vs -1.000000
-4.000000 vs -4.000000
-9.000000 vs -9.000000
-16.000000 vs -16.000000
-25.000000 vs -25.000000
```

**Comment by eschnett** [comment]
`nsimd-all.cpp` contains these lines:
```C++
  for (int i = 0; i < n; i++) {
    fprintf(stdout, "%f vs %f\n", double(buf[i]), double(-i * i));
  }

  for (int i = 0; i < n; i++) {
    if (buf[i] != float(-(i * i) + 1)) {
      exit(EXIT_FAILURE);
    }
  }
```

The `fprintf` outputs `-(i * i)`, the if condition checks `-(i * i) + 1`.
