### ISSUE TITLE
[setup.bat] change NSTOOLS_URL in setup.sh/setup.bat

### ISSUE THREAD

**Issue by ThomasRetornaz** [agenium-scale/nsimd#80]
Hi and thanks a lot for this library and congrats for V2
I'm facing issue related to build nstools on windows (MSVC 2019 14.28)
For fetching nstools the below url is used

`git@github.com:agenium-scale/nstools.git`

Which seems to require some user specific key
Changing to

`https://github.com/agenium-scale/nstools` 

Solve the pb

**Comment by gquintin** [comment]
Hi Thomas,

Thanks, I hope that v2 will be useful to you. Cocnerning the issue you are right. I focused on the Linux part of it and forgot to change the Windows script. I will do it as soon as possible.
