### ISSUE TITLE
Add support for CMake (CMakeLists.txt and FindNsimd.cmake as a start)

### ISSUE THREAD

**Issue by NK-Nikunj** [agenium-scale/nsimd#82]
Is there a FindNsimd.cmake file or similar structure to find nsimd through CMake, or a method to ease searching nsimd when using a CMake project?

**Comment by gquintin** [comment]
Hi Nikunj, at this point we do not have a FindNsimd.cmake file. We should add one. More generally anything that can facilitate the use of NSIMD is welcome.

**Comment by gquintin** [comment]
Hi Nikunj, let me change the title of your issue to a more general one.

**Comment by NK-Nikunj** [comment]
Hey @gquintin, it'll be nice to have one to ease building with Nsimd. I just wanted to make sure if there's one in existence (or in works). I'll use a workaround with a user-provided path for the time being.

**Comment by gquintin** [comment]
I have added a CMakeLists.txt. Do not hesitate to try it and tell us if it does not work properly.

**Comment by gquintin** [comment]
Hi Nikunj, I have added an undebugged version of [FindNSIMD.cmake](https://github.com/agenium-scale/nsimd/blob/master/scripts/FindNSIMD.cmake). I do not have time to debug it right now unfortunately. Feel free to test and debug it. I will come back at it as soon as I have finished my other urgent stuff.

**Comment by gquintin** [comment]
Hi Nikunj, I have debugged CMakeLists.txt and FindNSIMD.cmake. I will update the README on how to use these. I mark this issue as resolved.
