### ISSUE TITLE
Provide cbrt

### ISSUE THREAD

**Issue by eschnett** [agenium-scale/nsimd#87]
`cbrt` is an ANSI C math function. It would be convenient if it was supported in nsimd, instead of having to fall back to scalar code.

**Comment by gquintin** [comment]
`cbrt` is part of Sleef whose math functions will be available through the NSIMD APIs as well as many other. I opened the issue concerning Sleef (wanted to do it for a moment now but did not have time) thanks to this issue. Therefore I am closing this issue as it will be solved automatically when the Sleef issue will be.

Sleef issue = <https://github.com/agenium-scale/nsimd/issues/91>
