### ISSUE TITLE
Provide fabs, fmax, fmin

### ISSUE THREAD

**Issue by eschnett** [agenium-scale/nsimd#90]
The C++ standard provides `fabs`, `fmax`, and `fmin`, with the same meaning as `abs`, `max`, and `min`. It would be convenient to have these available for `nsimd::pack` as well.

**Comment by gquintin** [comment]
I assume you need them for writing code that can work on both SIMD vectors and scalars? If this is correct it means that it is only a C++ matter concerning the advanced API. As a consequence I don't think that adding them as operators is good. Instead I will create a new header called `cxx_adv_api_aliases.hpp` that will contain the functions that can be found in C++ standard that you need. This header will of course be included automatically by `nsimd-all.hpp`.

**Comment by eschnett** [comment]
This sounds good.
