### ISSUE TITLE
Implement a `flipsign` function

### ISSUE THREAD

**Issue by eschnett** [agenium-scale/nsimd#93]
I find the non-standard `flipsign` function https://docs.julialang.org/en/v1/base/math/#Base.flipsign convenient, e.g. to implement upwind finite differencing stencils. It can be defined as
```
flipsign(x, y) = copysign(1, y) * x
```
but can be implemented more efficiently as
```
flipsign(x, y) = x ^ (y & SIGNMASK)
```

**Comment by gquintin** [comment]
If you allow me, I will "merge" this issue with #92 to have all this operators at one place.
