### ISSUE TITLE
Feature request: allow logical arguments for if_else1

### ISSUE THREAD

**Issue by eschnett** [agenium-scale/nsimd#99]
I want to blend two logical expressions, as in:
```C++
simdl<double> cond;
simdl<double> x, y;
simdl<double> r = if_else1(cond, x, y);
```

There is currently no intrinsic for this.

I can express this as `(cond && x) || (!cond && y)`, but a dedicated intrinsic might lead to better code.

**Comment by gquintin** [comment]
Hi Erik, I am not sure I understand your question correctly. I think this is already the case. As you can see at <https://agenium-scale.github.io/nsimd/wrapped_intrinsics.html> we have wrapped the blend instructions for Intel SIMD. For Arm we have wrapped the bsl/sel instructions.

Also note that the first argument must be a pack of logicals. For the base C and C++ APIs as we use the native types then for all SIMD extensions except AVX-512 and SVE the logical types are the same as the arithmetic types. When using the advanced (upcoming C11) and C++ APIs then as native SIMD types are boxed into struct you have to use a `nsimd::packl` as the first argument to `if_else1`.

Note also that we have defined `if_else` that takes as a first argument a `nsimd::packl<S>` as long as `sizeof(S) == sizeof(T)`:

```c++
void foo() {
    nsimd::pack<float> a, b, c;
    nsimd::packl<float> lf;
    a = nsimd::if_else(lf, b, c); // corect

    nsimd::packl<int> li;
    a = nsimd::if_else(li, b, c); // correct

    nsimd::packl<short> ls;
    a = nsimd::if_else(ls, b, c); // incorrect

    nsimd::packl<double> ld;
    a = nsimd::if_else(ld, b, c); // incorrect
}
```

**Comment by gquintin** [comment]
In the meantime, as a workaround, maybe you can use:

```c++
r = to_logical(if_else(cond, to_mask(x), to_mask(y)));
```

**Comment by eschnett** [comment]
I realize I was confused. I accidentally declared the result as `simd<double>` instead of `simdl<double>`, and misinterpreted the error message. The functionality I was looking for is already there, as you describe.
